Book.create(inout: 1, category: "給与", year: 2020, month: 7, amount: 30)
Book.create(inout: 2, category: "家賃", year: 2020, month: 7, amount: 8)
Book.create(inout: 3, category: "食費", year: 2020, month: 7, amount: 6)
Book.create(inout: 4, category: "光熱費・水道", year: 2020, month: 7, amount: 3)
Book.create(inout: 5, category: "保険", year: 2020, month: 7, amount: 2)
